server:
  port: 8086

spring:
  application:
    name: db-service
  datasource:
    url: jdbc:mysql://localhost:3306/prizent_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Adarsh@.27'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.elowen.db: DEBUG
